package dev.dimension.flare.data.network.discourse.realtime

import io.ktor.http.URLProtocol
import io.ktor.http.Url
import kotlinx.serialization.json.JsonElement

/**
 * Cursor used for a new subscription that should start at the current MessageBus head.
 *
 * Discourse gives `-1` a protocol meaning: do not replay backlog for this channel. Persisted
 * cursors are non-negative message IDs; keeping the sentinel named avoids scattering a magic
 * number through foreground lifecycle code.
 */
public const val DISCOURSE_MESSAGE_BUS_INITIAL_CURSOR: Long = -1L

internal const val MAX_DISCOURSE_MESSAGE_BUS_SAFE_INTEGER: Long = 9_007_199_254_740_991L
internal const val MIN_DISCOURSE_MESSAGE_BUS_RELATIVE_CURSOR: Long = -1_000L
internal const val MAX_DISCOURSE_MESSAGE_BUS_CHANNELS: Int = 64
internal const val MAX_DISCOURSE_MESSAGE_BUS_CHANNEL_LENGTH: Int = 256

/**
 * Immutable input for one MessageBus long poll.
 *
 * A client ID uses the undashed lowercase UUID-v4 shape generated by Discourse's browser client.
 * Channel names are deliberately restricted to absolute ASCII paths so neither the request path
 * nor JSON keys can smuggle control characters. [sequence] is the monotonically increasing poll
 * sequence owned by the higher-level coordinator. Channel cursors may use the small negative range
 * supported by MessageBus for relative backlog requests, including
 * [DISCOURSE_MESSAGE_BUS_INITIAL_CURSOR].
 */
public class DiscourseMessageBusPollRequest(
    public val clientId: String,
    public val sequence: Long,
    channels: Map<String, Long>,
    public val endpoint: DiscourseMessageBusEndpoint = DiscourseMessageBusEndpoint.SameOrigin,
) {
    /** A stable snapshot; later mutation of the caller's map cannot alter an in-flight request. */
    public val channels: Map<String, Long> = channels.toMap()

    init {
        require(isValidDiscourseMessageBusClientId(clientId)) {
            "MessageBus client ID must be a lowercase undashed UUID v4"
        }
        require(sequence in 1L..MAX_DISCOURSE_MESSAGE_BUS_SAFE_INTEGER) {
            "MessageBus sequence is outside the interoperable integer range"
        }
        require(this.channels.isNotEmpty() && this.channels.size <= MAX_DISCOURSE_MESSAGE_BUS_CHANNELS) {
            "MessageBus poll must contain a bounded non-empty channel set"
        }
        this.channels.forEach { (channel, cursor) ->
            require(isValidDiscourseMessageBusChannel(channel) && channel != DISCOURSE_MESSAGE_BUS_STATUS_CHANNEL) {
                "MessageBus subscription channel is invalid"
            }
            require(cursor in MIN_DISCOURSE_MESSAGE_BUS_RELATIVE_CURSOR..MAX_DISCOURSE_MESSAGE_BUS_SAFE_INTEGER) {
                "MessageBus cursor is outside the interoperable integer range"
            }
        }
    }
}

/**
 * Explicit network boundary for MessageBus polling.
 *
 * [SameOrigin] is the default and uses the protected Linux.do cookie client. [CrossOrigin] and
 * [SharedSession] represent Discourse's optional `long_polling_base_url` deployment: both must use
 * a different, public-looking HTTPS origin and a separate cookie-less client. Anonymous sessions
 * use [CrossOrigin] without credentials, while authenticated sessions require [SharedSession] and
 * send its ephemeral key only through `X-Shared-Session-Key`.
 */
public sealed class DiscourseMessageBusEndpoint private constructor() {
    /** Poll `https://linux.do/message-bus/...` with the generation-bound session cookie client. */
    public data object SameOrigin : DiscourseMessageBusEndpoint()

    /** Poll a public cross-origin MessageBus endpoint without cookies or authentication headers. */
    public class CrossOrigin(
        pollingOrigin: String,
    ) : DiscourseMessageBusEndpoint() {
        /** Normalized HTTPS origin without a trailing slash. */
        public val pollingOrigin: String = normalizeCrossOrigin(pollingOrigin)

        override fun toString(): String = "DiscourseMessageBusEndpoint.CrossOrigin(pollingOrigin=$pollingOrigin)"
    }

    /**
     * Poll a separately configured Discourse MessageBus origin with its ephemeral shared key.
     *
     * Discourse currently generates a 32-character lowercase hexadecimal key. The constructor
     * retains a defensive character copy and [toString] always redacts it. A MessageBus run owns
     * the endpoint and erases that copy when its generation lease ends; providers must therefore
     * return a fresh instance for each resolution and never persist the key.
     */
    public class SharedSession(
        pollingOrigin: String,
        sharedSessionKey: String,
    ) : DiscourseMessageBusEndpoint() {
        /** Normalized HTTPS origin without a trailing slash. */
        public val pollingOrigin: String = normalizeCrossOrigin(pollingOrigin)

        private val keyCharacters: CharArray = requireValidSharedSessionKey(sharedSessionKey)

        private var cleared: Boolean = false

        internal fun headerValue(): String {
            check(!cleared) { "Discourse shared session key is no longer available" }
            return keyCharacters.concatToString()
        }

        internal fun clear() {
            keyCharacters.fill('\u0000')
            cleared = true
        }

        internal fun isCleared(): Boolean = cleared && keyCharacters.all { it == '\u0000' }

        override fun toString(): String =
            "DiscourseMessageBusEndpoint.SharedSession(pollingOrigin=$pollingOrigin, sharedSessionKey=<redacted>)"
    }
}

private fun requireValidSharedSessionKey(sharedSessionKey: String): CharArray {
    require(sharedSessionKey.length == 32 && sharedSessionKey.all { it in '0'..'9' || it in 'a'..'f' }) {
        "Discourse shared session key has an invalid shape"
    }
    return sharedSessionKey.toCharArray()
}

private fun normalizeCrossOrigin(pollingOrigin: String): String {
    val parsed =
        try {
            Url(pollingOrigin)
        } catch (_: IllegalArgumentException) {
            throw IllegalArgumentException("Discourse MessageBus polling origin is invalid")
        }
    require(parsed.protocol == URLProtocol.HTTPS) { "Discourse MessageBus polling origin must use HTTPS" }
    require(
        parsed.port == URLProtocol.HTTPS.defaultPort &&
            (parsed.specifiedPort == 0 || parsed.specifiedPort == URLProtocol.HTTPS.defaultPort),
    ) {
        "Discourse MessageBus polling origin must use the default HTTPS port"
    }
    require(parsed.user == null && parsed.password == null) {
        "Discourse MessageBus polling origin cannot contain user info"
    }
    require(
        parsed.encodedPath.isEmpty() || parsed.encodedPath == "/",
    ) { "Discourse MessageBus polling origin cannot contain a path" }
    require(parsed.parameters.isEmpty() && !parsed.trailingQuery && parsed.fragment.isEmpty()) {
        "Discourse MessageBus polling origin cannot contain a query or fragment"
    }
    require(isValidCrossOriginHost(parsed.host)) { "Discourse MessageBus polling host is invalid" }
    require(!parsed.host.equals("linux.do", ignoreCase = true)) {
        "Linux.do must use the same-origin cookie transport"
    }
    return "https://${parsed.host}"
}

/** One JSON array delivered by a normal response or one frame of a chunked response. */
public class DiscourseMessageBusBatch(
    events: List<DiscourseMessageBusEvent>,
) {
    /** A stable list so transport validation cannot be invalidated after emission. */
    public val events: List<DiscourseMessageBusEvent> = events.toList()
}

/** Validated envelope emitted by the low-level Linux.do MessageBus transport. */
public sealed interface DiscourseMessageBusEvent {
    public val globalId: Long
    public val messageId: Long
    public val channel: String
}

/**
 * A normal channel message.
 *
 * [data] remains JSON because each Discourse channel owns a different schema. Consumers must map
 * only their channel's allowlisted fields before the value crosses into durable or presentation
 * state. Unknown envelope fields are discarded by the transport serializer.
 */
public data class DiscourseMessageBusMessage(
    override val globalId: Long,
    override val messageId: Long,
    override val channel: String,
    public val data: JsonElement,
) : DiscourseMessageBusEvent

/**
 * Discourse's synthetic `/__status` event, used to advance channels when backlog was unavailable or
 * filtered by server-side authorization.
 *
 * Only validated channel-to-cursor entries are retained; arbitrary status payload fields never
 * leave the transport boundary.
 */
public class DiscourseMessageBusStatus(
    override val globalId: Long,
    override val messageId: Long,
    cursors: Map<String, Long>,
) : DiscourseMessageBusEvent {
    override val channel: String = DISCOURSE_MESSAGE_BUS_STATUS_CHANNEL

    public val cursors: Map<String, Long> = cursors.toMap()
}

internal const val DISCOURSE_MESSAGE_BUS_STATUS_CHANNEL: String = "/__status"

internal fun isValidDiscourseMessageBusClientId(value: String): Boolean {
    if (value.length != 32 || value[12] != '4' || value[16] !in "89ab") return false
    return value.all { it in '0'..'9' || it in 'a'..'f' }
}

/**
 * MessageBus channel grammar used by Linux.do's latest/new/topic/notification/reaction routes.
 * Empty segments, a trailing slash, non-ASCII characters, and URI metacharacters are rejected.
 */
internal fun isValidDiscourseMessageBusChannel(value: String): Boolean {
    if (value.length !in 2..MAX_DISCOURSE_MESSAGE_BUS_CHANNEL_LENGTH || value.first() != '/') return false
    if (value.last() == '/') return false
    var previousWasSlash = true
    value.drop(1).forEach { character ->
        if (character == '/') {
            if (previousWasSlash) return false
            previousWasSlash = true
        } else {
            val safe =
                character in 'a'..'z' ||
                    character in 'A'..'Z' ||
                    character in '0'..'9' ||
                    character == '_' ||
                    character == '-' ||
                    character == '.' ||
                    character == '@' ||
                    character == ':' ||
                    character == '+'
            if (!safe) return false
            previousWasSlash = false
        }
    }
    return !previousWasSlash
}

private fun isValidCrossOriginHost(host: String): Boolean {
    if (
        host.length !in 4..253 ||
        host != host.lowercase() ||
        '.' !in host ||
        host.none { it in 'a'..'z' }
    ) {
        // A cross-origin poll endpoint must be a DNS name. Requiring an ASCII letter rejects every
        // IPv4 literal; the label grammar below already rejects IPv6 brackets and colons.
        return false
    }
    val labels = host.split('.')
    return labels.all { label ->
        label.length in 1..63 &&
            label.first() != '-' &&
            label.last() != '-' &&
            label.all { it in 'a'..'z' || it in '0'..'9' || it == '-' }
    }
}
